#!/usr/bin/env python
#author cjsund@126.com
import os
import sys
import stat
import shutil

paths = sys.path[0].split('/')
root_path = '/'.join(paths[:len(paths)-1])
bin_path = os.path.join(root_path, 'bin')
bin_file = os.listdir(bin_path)

def checkuser():
	if os.getlogin() is not "root":
		print "Error: You need as root!"
		sys.exit(1)

def checkorder(order):
	if os.path.exists(order):
		print "\033[35m backup is already install! \033[0m"
		sys.exit(1)

def install():
	try:
		for i in bin_file:
			shutil.copyfile(os.path.join(bin_path, i), "/usr/bin/%s" % i)
			os.chmod("/usr/bin/%s" % i, stat.S_IRWXU + stat.S_IXGRP + stat.S_IRGRP + stat.S_IROTH + stat.S_IXOTH)
			print "\033[32m Install success! \033[0m"
			print "\033[32m cp %s to /usr/bin/%s \033[0m" % (i, i)
	except IOError, e:
			print "\033[31m %s\033[0m" % e
	
if __name__ == '__main__':
	checkuser()
	if len(sys.argv) is 2:
		if sys.argv[1] == 'update':
			install()
		else:
			print "\033[31m Please check option! \033[0m"
	elif len(sys.argv) is 1:
		checkorder("/usr/bin/backup")
		install()
	else:
		print "\033[31m Please check option! \033[0m"