#!/usr/bin/env python

import os
import sys
import stat
import shutil

paths = sys.path[0].split('/')
root_path = '/'.join(paths[:len(paths)-1])
bin_path = os.path.join(root_path, 'bin')
bin_file = os.listdir(bin_path)

try:
	for i in bin_file:
		shutil.copyfile(os.path.join(bin_path, i), "/usr/bin/%s" % i)
		os.chmod("/usr/bin/%s" % i, stat.S_IRWXU + stat.S_IXGRP + stat.S_IRGRP + stat.S_IROTH + stat.S_IXOTH)
		print "\033[32m Install success! \033[0m"
		print "\033[32m cp %s to /usr/bin/%s \033[0m" % (i, i)
except IOError, e:
		print "\033[31m %s\033[0m" % e

