#!/usr/bin/env bash
#author cjsund@126.com

url="https://raw.githubusercontent.com/cjsund/lazy_tools/master/bin/backup"

checkorder(){
	if [[ -f "/usr/bin/backup" ]]; then
		echo " backup is already install! "
		exit 1
	fi
}

install(){
	cd /tmp

	wget $url --no-check-certificate > /dev/null 2>&1

	mv -f backup /usr/bin/backup
	if [ $? == 0 ]
	then
        chmod +x /usr/bin/backup
		echo " Install seccess! "
	fi
}

if [[ `whoami` != 'root' ]]; then
	echo "ERROR: You need as root!"
	exit 2
fi

if [[ $# -eq 1 ]]; then
	case "$1" in
		update )
			install
			;;
		* )
			echo " Please check option! "
			;;
	esac
elif [[ $# -eq 0 ]];then
	checkorder
	install
else
	echo " Please check option! "
fi
